seed_everything: 42

data:
  class_path: data_model.datamodel.MySEQDataModule
  init_args:
    data_name: Mnist
    pca_dim: 64
    batch_size: 200
    num_workers: 6
    K: 5
    n_f_per_cluster: 3
    l_token: 10
    data_path: /zangzelin/data

model:
  class_path: model.tran_exp_pacmap.DMTEVT_model
  init_args:
    num_input_dim: 784
    seq_len: 784
    sigma: 0.5
    lr: 0.001
    w_nb: 1
    w_fp: 1
    weight_mse: 10
    weight_nepo: 1
    sample_rate_feature: 0.7
    tau: 2
    T_num_layers: 1
    T_num_attention_heads: 10
    T_hidden_size: 2000
    T_intermediate_size: 300
    T_hidden_dropout_prob: 0
    T_attention_probs_dropout_prob: 0
    ckpt_path: 'zzl_checkpoints/11Mar_mnist-epoch=02999.ckpt'

trainer:
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: test
      project: DMTNML
      save_dir: wandb
  callbacks:
    - class_path: call_backs.EvalAcc.EvalCallBack
      init_args:
        inter: 10
    - class_path: call_backs.MaskExp.MaskExpCallBack
      init_args:
        inter: 10
    - class_path: call_backs.Logtau.LogTauCallBack
      init_args:
        inter: 10
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        # monitor: 'SVC_val'
        dirpath: 'zzl_checkpoints/'  
        filename: 'mnist-{epoch:05d}'  
        # save_top_k: 3  
        # mode: 'max'  
        every_n_epochs: 50 
  max_epochs: 300
  devices: 6
  accelerator: gpu
  gradient_clip_val: 0.005
  gradient_clip_algorithm: 'norm'
  check_val_every_n_epoch: 25
  strategy: 'deepspeed'
  precision: 16
  # enable_checkpointing: False
