seed_everything: 42

data:
  batch_size: 100
  num_workers: 4
  data_name: Mnist
  K: 5
  pca_dim: 784
  n_f_per_cluster: 3
  l_token: 10
  sample_len: 500
  data_path: /zangzelin/data

model:
  class_num: 10
  l_token: 50
  sample_len: 500
  num_input_dim: 784
  num_layers_Transformer: 6
  l_token_2: 50
  nu: 0.1

trainer:
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: test
      project: DMTEVT
      save_dir: wandb
  # callbacks:
  #   - class_path: lightning.pytorch.callbacks.ModelCheckpoint
  #     init_args:
  #       monitor: SVC_train
  #       dirpath: ./checkpoints
  #       filename: mnist-best-{epoch:03d}-{SVC_train:.5f}
  #       save_top_k: 2
  #       mode: max
  max_epochs: 800
  devices: [0]
  accelerator: gpu
  check_val_every_n_epoch: 50
  enable_checkpointing: True
  enable_progress_bar: True
  # strategy: ddp_find_unused_parameters_true
# trainer.strategy: ddp