data:
  class_path: data_model.datamodel.MyDataModule
  init_args:
    K: 3
    batch_size: 651404
    data_name: Activity
    data_path: /zangzelin/data
    l_token: 10
    n_f_per_cluster: 3
    num_workers: 5
    pca_dim: 128
model:
  class_path: model.baseline.DMTEVT_model
  init_args:
    early_exaggeration: 12
    method: tsne
    n_components: 2
    num_input_dim: 64
    perplexity: 30
seed_everything: 42
trainer:
  accelerator: gpu
  callbacks:
  - class_path: call_backs.EvalAcc_high_low_emb_baseline.EvalCallBack
    init_args:
      dataset: mnist
      dirpath: zzl_checkpoints/
      inter: 1
  check_val_every_n_epoch: 1
  devices: 1
  enable_checkpointing: false
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: test
      project: DMTNML
      save_dir: wandb
  max_epochs: 1
